name : test image generation
run-name :  running test for typescript bun image generation script
on : [push]

jobs:
  run-tests-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun i 
        working-directory: ./js/ts
      - name: Run tests
        run: bun tests/testsMain.ts
        working-directory: ./js/ts
